default: dev

# Show this info message
help:
  just --list

dev:
    RUST_LOG="niku_backend=debug,info" cargo run

trace:
    RUST_LOG="niku_backend=trace,debug" cargo run

# Fix any fixable problem on the crates
fix:
    cargo fix --allow-dirty --allow-staged -p niku_backend
    cargo +nightly fmt -p niku_backend