[package]
name = "uniffi_bindgen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"

[lints]
workspace = true
